from PyQt6.QtWidgets import (
    QWidget, QPushButton, QVBoxLayout, QLabel, QMessageBox, QLineEdit
)
from PyQt6.QtCore import Qt
from models.vote_manager import VoteManager
from views.results_window import ResultsWindow

# Disclosure: portions of this file were generated by AI.
# I reviewed and edited the code for the assignment requirements.

class MainWindow(QWidget):
    """Main GUI window for voting.

    This window asks the user for a Voter ID (simple text) and lets them cast
    one vote. The VoteManager enforces "one vote per voter".
    """

    def __init__(self) -> None:
        super().__init__()
        self.setWindowTitle("Voting System")
        self.manager = VoteManager()

        # UI elements
        self.label = QLabel("Enter your Voter ID and select a candidate.")
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.input_voter = QLineEdit()
        self.input_voter.setPlaceholderText("Enter voter ID (no spaces)")

        self.btn_isabella = QPushButton("Vote Isabella")
        self.btn_genji = QPushButton("Vote Genji")
        self.btn_hannah = QPushButton("Vote Hannah")

        self.btn_results = QPushButton("View Results")
        self.btn_exit = QPushButton("Save & Exit")

        # layout
        layout = QVBoxLayout()
        layout.addWidget(self.label)
        layout.addWidget(self.input_voter)
        layout.addWidget(self.btn_isabella)
        layout.addWidget(self.btn_genji)
        layout.addWidget(self.btn_hannah)
        layout.addWidget(self.btn_results)
        layout.addWidget(self.btn_exit)
        self.setLayout(layout)

        # connections
        self.btn_isabella.clicked.connect(lambda: self.cast_vote("Isabella"))
        self.btn_genji.clicked.connect(lambda: self.cast_vote("Genji"))
        self.btn_hannah.clicked.connect(lambda: self.cast_vote("Hannah"))
        self.btn_results.clicked.connect(self.show_results)
        self.btn_exit.clicked.connect(self.exit_app)
    def _validate_voter_id(self, voter_id: str) -> bool:
        """Simple validation for voter id: can't be empty, has to be short, and no commas or newlines."""
        if not isinstance(voter_id, str):
            return False
        voter = voter_id.strip()
        if not voter:
            return False
        if len(voter) > 64:
            return False
        # no commas or newlines
        if any(char in voter for char in [",", "\n", "\r"]):
            return False
        return True

    def cast_vote(self, candidate: str) -> None:
        """Handles vote button clicks; validates voter id and registers vote."""
        voter_id = self.input_voter.text()
        if not self._validate_voter_id(voter_id):
            QMessageBox.warning(self, "Invalid Voter ID", "Please enter a valid voter ID (no commas).")
            return

        try:
            success = self.manager.register_vote(voter_id, candidate)
        except ValueError as exc:
            QMessageBox.critical(self, "Error", str(exc))
            return
        except Exception:
            QMessageBox.critical(self, "Error", "Unexpected error when recording vote.")
            return

        if not success:
            QMessageBox.warning(self, "Already Voted",
                                "This voter ID has already been used to vote.")
        else:
            QMessageBox.information(self, "Vote Recorded",
                                    f"Thank you, {voter_id}. Your vote for {candidate} was recorded.")
            # optionally clear voter id to avoid reuse
            self.input_voter.clear()

    def show_results(self) -> None:
        """Opens the results window."""
        self.results_window = ResultsWindow(self.manager)
        self.results_window.show()

    def exit_app(self) -> None:
        """Saves data and closes the app."""
        self.manager.save()
        QMessageBox.information(self, "Saved", "Votes were saved.")
        self.close()
